
export const constants = {
    METHOD: { GET: 'GET', POST: 'POST', PUT: 'PUT', DELETE: 'DELETE' },
    INCIDENT_COTROLLER: 'INCIDENT_COTROLLER',
    GET_ALL_INCIDENTS_SUCCESS: 'GET_ALL_INCIDENTS_SUCCESS',
    ADD_INCIDENT_SUCCESS: 'ADD_INCIDENT_SUCCESS',
    UPDATE_INCIDENT_SUCCESS: 'UPDATE_INCIDENT_SUCCESS',
    GET_INCIDENT_BY_ID_SUCCESS: 'GET_INCIDENT_BY_ID_SUCCESS',
    INCIDENT_NOT_FOUND: 'INCIDENT_NOT_FOUND',
    ERROR_GETTING_ALL_INCIDENTS: 'ERROR_GETTING_ALL_INCIDENTS',
    ERROR_ADDING_INCIDENT: 'ERROR_ADDING_INCIDENT',
    MISSNG_REQUIRED_FIELDS: 'MISSNG_REQUIRED_FIELDS',
    ERROR_AGGGREATION: 'ERROR_AGGGREATION',
    TIMELINE_EVENT: 'TIMELINE_EVENT',
    INCIDENT_SERVICE: 'INCIDENT_SERVICE',
    TAG_SERVICE:'TAG_SERVICE',
    NOT_FOUND:'NOT_FOUND',
    BAD_REQUEST:'BAD_REQUEST',
    INDEX_NOT_VALID:'INDEX_NOT_VALID'
}

