export const status = {
    SUCCESS: 200,
    CREATED_SUCCESS: 201,
    BAD_REQUEST: 400,
    PAGE_NOT_FOUND: 404,
    MISSNG_REQUIRED_FIELDS: 422,
    SERVER_ERROR: 500,
  };

  export const files={
    CREATEINCIDENT:"actions/via-slack/createIncident.ts",
    CREATETIMELINE:"actions/via-slack/createTimeline.ts",
    FILERESPONSE:"actions/via-slack/fileResponse.ts",
    CREATECHANNEL:"actions/via-ims/createChannel.ts",
    SENDMESSAGEONADDTIMELINEEVENT:"actions/via-ims/sendMessageOnAddTimelineEvent.ts",
    UPDATE_CHANNEL_DESCRIPTION:"actions/base/updateChannelDescription.ts",
    SEND_MESSAGE:"actions/base/sendMassage.ts",
    OPEN_DIRECT_MESSAGE_WITH_BOT:"actions/base/openDirectMessageWithBot.ts",
    JOIN_BOT_TO_CHANNEL:"actions/base/joinBotToChannels.ts",
    INVITE_PEOPLE_TO_CHANNEL:"actions/base/InvitePeopleToChannel.ts",
    GET_USERS:"actions/base/getUsers.ts",
    GET_SLACK_DATA:"actions/base/getSlackDataByChannelId.ts",
    CREATE_CHANNEL:"actions/base/createChannel.ts",
    SLACK_TRACKING:"slackTracking.ts",
    SOCKET:"socket.ts",
    APP:"app.ts"
  }
  

  export const constants = {
    METHOD: { GET: "GET", POST: "POST", PUT: "PUT", DELETE: "DELETE",CLIENT:"slack-client" },
    CHANNEL_NOT_FOUND_IN_SLACK : "Channel not found in Slack",
    ERROR_CREATING_INCIDENT : "Error creating incident:",
    ERROR_CREATING_TIMELINEEVENT:"error creating timelineevent",
    AXIOS_ERROR_GET_INCIDENT_BY_CHANNELID:"error get incident by channelID",
    AXIOS_ERROR_EXTRACTING_FILES : 'Error extracting files:',
    AXIOS_ERROR_UPLOAD_FILES_TO_S3:'AXIOS_ERROR_UPLOAD_FILES_TO_S3',
    ERROR_CREATING_CHANNEL : 'Error creating channel:',
    AXIOS_ERROR_COMPAREINCIDENTCHANGES:"AXIOS_ERROR_COMPAREINCIDENTCHANGES",
    CHANNEL_DESCRIPTION_UPDATED:"Channel description updated:",
    CLIENT_ERROR_UPDATING_CHANNEL_DESCRIPTION : 'Error updating channel description:',
    CLIENT_ERROR_POST_MASSAGE:"CLIENT_ERROR_POST_MASSAGE",
    CLIENT_ERROR_SENDING_FILES_TO_SLACK:'Error sending files to slack:',
    MESSAGE_SENDING_MESSAGE_SUCCESSFULLY:'Message sent successfully!',
    CLIENT_ERROR_OPEN_DIRECT_MESSAGE_WITH_BOT:"CLIENT_ERROR_OPEN_DIRECT_MESSAGE_WITH_BOT",
    BOT_SUCCESSFULLY_JOINED_CHANNEL:"Bot successfully joined channel",
    CLIENT_ERROR_JOIN_BOT_TO_CHANNEL:"CLIENT_ERROR_JOIN_BOT_TO_CHANNEL",
    SUCCESSFULLY_INVITE_PEOPLE_TO_CHANNEL:"SUCCESSFULLY_INVITE_PEOPLE_TO_CHANNEL",
    CLIENT_ERROR_INVITE_PEOPLE_TO_CHANNEL:"CLIENT_ERROR_INVITE_PEOPLE_TO_CHANNEL",
    SUCCESSFULLY_GET_USERS_IN_SLACK:"SUCCESSFULLY_GET_USERS_IN_SLACK",
    CLIENT_ERROR_GET_USERS_IN_SLACK:"CLIENT_ERROR_GET_USERS_IN_SLACK",
    CLIENT_ERROR_GETTING_SLACK_CHANNEL_DATA:"Error getting Slack Channel data",
    SUCCESSFULLY_GET_SLACK_DATA:"SUCCESSFULLY_GET_SLACK_DATA",
    CLIENT_ERROR_GET_SLACK_DATA:"CLIENT_ERROR_GET_SLACK_DATA",
    CLIENT_ERROR_CREATING_CHANNEL:"CLIENT_ERROR_CREATING_CHANNEL",
    SUCCESSFULLY_CREATING_CHANNEL:"SUCCESSFULLY_CREATING_CHANNEL",
    SERVER_STARTED_PORT_4701:"SERVER_STARTED_PORT_4701",
    FILED_HANDLE_EVENT:"Unhandled event type:",
    SOCKET_ERROR_RECEIVED_UNKNOWN_OBJECT_TYPE:"Received unknown object type:",
    SOCKET_ERROR_RECEIVED_UNKNOWN_ACTION_TYPE_FOR_TIMELINE:"Received unknown action type for TimelineEvent:",
    SOCKET_ERROR_RECEIVED_UNKNOWN_ACTION_TYPE_FOR_INCIDENT:"'Received unknown action type for Incident:'",
    SOCKET_WEBSOCKET_CONNECTION_IS_OPEN:"WebSocket connection is open in ims-slack",
    SERVER_IS_OS_IN_LOCALHOST_PORT:"Server is on http://localhost:"
  };